rename psp20 to psp17, add ipsp17receiver
Supercolony-net/PSPs pull request #2
Opened 2021-06-24 13:01 UTC by VargSupercolony

2021-06-24 13:22 UTC, xgreenx commented on PSPs/drafts/psp-17.md
> + TransferRejected(String),
&'static str

2021-06-24 13:22 UTC, xgreenx commented on PSPs/drafts/psp-17.md
> + fn on_psp17_received(&mut self, operator: AccountId, from: AccountId, value: Balance, data: Vec<u8>) -> Result<(), PSP17ReceiverError>;
You need to describe behavior of this trait somewhere. For example like in solidity via comments

2021-06-24 15:20 UTC, xgreenx approved these changes

2021-06-25 08:06 UTC, xgreenx requested changes

2021-06-25 08:06 UTC, xgreenx commented on PSPs/drafts/psp-17.md
>   Unknown(&'static str),
String here too

2021-06-25 13:14 UTC, xgreenx approved these changes

2021-06-25 13:44 UTC, PierreOssun approved these changes
Ok for me

2021-06-25 14:00 UTC, sventime commented on PSPs/drafts/psp-17.md
> + Unknown(String),
Let's maybe call it Custom. It substrate they will do the same for dymanic errors: https://github.com/paritytech/substrate/issues/5239#issuecomment-858451861

2021-06-26 17:04 UTC, merged