Moved description of methods to traits
Supercolony-net/PSPs pull request #4
Opened 2021-06-27 23:29 UTC by xgreenx

Moved description of methods to traits
Added short description of each trait.
Added `data` argument to transfer function(which can be passed to `on_received`

2021-06-29 06:40 UTC, VargSupercolony requested changes
great overall, just minor mistakes

2021-06-29 06:40 UTC, VargSupercolony commented on PSPs/psp-17.md
> + /// the caller's account Balance.
balance should be lowercased, it refers to literal balance, not the type in ink!.

2021-06-29 06:40 UTC, VargSupercolony commented on PSPs/psp-17.md
> + /// Atomically increases the allowance granted to `spender` by the caller on `delta_value`.
"on" should be changed to "by" ("by `delta_value`")

2021-06-29 06:40 UTC, VargSupercolony commented on PSPs/psp-17.md
> + /// Atomically decreases the allowance granted to `spender` by the caller on `delta_value`.
same here, on -> by

2021-06-29 08:05 UTC, VargSupercolony approved these changes
moved description of methods to trait

2021-06-30 12:34 UTC, sventime reviewed
Let's rename Unknown error to Custom

2021-06-30 12:34 UTC, sventime commented on PSPs/psp-17.md
> +/// PSP17 is a trait of Fungible Token Standard
Add a .

2021-06-30 17:25 UTC, themarkian approved these changes

2021-06-30 17:25 UTC, merged